name: flutter_feb
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  dots_indicator: ^1.0.0
  flutter_sparkline: ^0.1.0
  custom_switch: ^0.0.1
  rounded_floating_app_bar: ^0.1.0

  # 28/02/2020
  circular_check_box: ^1.0.1





dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  Travel App 21/02/2020
   - assets/2102/paris.jpg
   - assets/2102/england.jpg
   - assets/2102/japan.jpg
   - assets/2102/italya.jpg
   - assets/2102/tokyo.jpg
   - assets/2102/tokyo2.jpg
   - assets/2102/tokyo3.jpg
   - assets/2102/tokyo4.jpg
   - assets/2102/tokyo5.jpg

   #2402
   - assets/2402/airconditioner.png
   - assets/2402/humidity.png
   - assets/2402/lamp.png
   - assets/2402/light.png
   - assets/2402/temp.png
   - assets/2402/fan.png
   - assets/2402/back1.jpg
   - assets/2402/back2.jpg
   - assets/2402/back3.jpg
   - assets/2402/back4.jpg
   
   #2502
   - assets/2502/back1.jpg
   - assets/2502/back2.jpg
   - assets/2502/zenicon.png
   - assets/2502/moonicon.png
   - assets/2502/morningicon.png

   #2802
   - assets/2802/signin.jpg
   

   
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
